### ISSUE TITLE
Data text file.

### ISSUE THREAD

**Issue by mahfuj9346449** [thuml/HashNet#1]
How we can make our own data text file? Yor provided the data text file like this. Can you explain please?

./data/nuswide_81/images/98796_381708603_f86eb60ccf_m.jpg 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

**Comment by caozhangjie** [comment]
In your example, ``./data/nuswide_81/images/98796_381708603_f86eb60ccf_m.jpg`` is the path of your image in your computer. You can download the dataset I provided and modify this path. The next 0 and 1 string is one-hot label of this image. For example, if you have ten categories and one image belongs to the 5th category, then the label is ``0 0 0 0 1 0 0 0 0 0`` with the 5th entry as 1. Or if your dataset has multiple labels for one image, such as the 5th and 8th categories of ten categories, then  the label is ``0 0 0 0 1 0 0 1 0 0`` with the 5th entry and the 8th entry as 1. In this text file, every line need to be in this form and no empty line at the end of the file.

**Comment by mahfuj9346449** [comment]
Thank you so much for your kind reply. For an example of office-31 dataset which has 31 classes.  For an image which belongs to category 2 (single label), it should be:
001.jpg 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

Is it possible to work with the following notation for single label:
001.jog 2
002.jpg 2
............

for multiple label:

0001.jpg 2 6
0002.jpg 2 8

**Comment by caozhangjie** [comment]
I'm sorry but you need to use the first one-hot form. The second form is not supported.

**Comment by mahfuj9346449** [comment]
Thank you so much for your reply.
