### ISSUE TITLE
I want ask a question about the dataset

### ISSUE THREAD

**Issue by JieLi1994** [thuml/HashNet#12]
I have read your data text file. In your data text file,i can get a instance like this: /home/caozhangjie/run-czj/dataset/nus_wide/42368_249918118_7f1a328add_m.jpg 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0

'' /home/caozhangjie/run-czj/dataset/nus_wide/42368_249918118_7f1a328add_m.jpg '' is the data path,right?   and the ''0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 '' is the label vector.  but ,in nus-wide dataset the length of label vector shoulde be 81,why your label vector length is just 21?

**Comment by caozhangjie** [comment]
Sorry, I do not find a text file like this. Could you please provide the path?

**Comment by JieLi1994** [comment]
@caozhangjie  thank u for your help, the path is /HashNet/pytorch/data/nus_wide/.

**Comment by caozhangjie** [comment]
I'm sorry. It's mistake. You can merge the text files (databasei (i=0,...,7) and testi (i=0,...,7)) in caffe/data/nuswide_81 and use them as database and test.

**Comment by JieLi1994** [comment]
@caozhangjie   Thank u,and i have another question,in your paper ,there is a ablation study, hashnet-c+,hashnet,hashnet-w, so does your pytorch implementation is hashnet-w or not?  
Is the caffe version fully implemented?

**Comment by caozhangjie** [comment]
I'm sorry for replying late. Both version are fully implemented. But the AlexNet in PyTorch perform not as well as that in Caffe. Thus, we use ResNet as backbone network in PyTorch. If you want to do the ablation study, you can read our code and remove the corresponding part in the code. If you have any question, feel free to ask me.
