### ISSUE TITLE
How to find the hash of an image

### ISSUE THREAD

**Issue by nilesharma** [thuml/HashNet#13]
I saw in the given database hash is already appended, can you please tell me how to find the hash explicitly?

Thanks
Nilesh

**Comment by caozhangjie** [comment]
Sorry, I'm not quite understand your question. If you want to get hash codes from our dataset, you can use our pre-trained model and use 'models/predict/dataset_name/predict_parallel.py' to predict codes for every image. If it is your own dataset, you need to train your model with our training instructions and then predict.

**Comment by nilesharma** [comment]
Thank you very much, issue has been resolved
