### ISSUE TITLE
How to give prefix/snapshot in the argument

### ISSUE THREAD

**Issue by nilesharma** [thuml/HashNet#14]
Hello,

How to give prefix in the argument? do we need to create any folder for the prefix/snapshot??

**Comment by nilesharma** [comment]
When I run the command it gave me this below error

[cloudera@quickstart src]$ python train.py --gpu_id 0 --dataset coco --prefix resnet50_hashnet --hash_bit 48 --net ResNet50 --lr 0.0003 --class_num 1.0
Traceback (most recent call last):
  File "train.py", line 246, in <module>
    os.mkdir(config["output_path"])
OSError: [Errno 13] Permission denied: '/coco_48bit_resnet50_hashnet'

**Comment by nilesharma** [comment]
when I executed the command "python train.py --gpu_id 0 --dataset coco --prefix resnet50_hashnet --hash_bit 48 --net ResNet50 --lr 0.0003 --class_num 1.0"

it game this below error

[cloudera@quickstart src]$ python train.py --gpu_id 0 --dataset coco --prefix resnet50_hashnet --hash_bit 48 --net ResNet50 --lr 0.0003 --class_num 1.0
Traceback (most recent call last):
  File "train.py", line 246, in <module>
    os.mkdir(config["output_path"])
OSError: [Errno 13] Permission denied: '/coco_48bit_resnet50_hashnet'

**Comment by caozhangjie** [comment]
The path is where you save your code. Sample code is here: 'np.save(opath.join(path, "database_code.npy"), database_code)'. You cannot make a dir in root dir if you run without root permission.
