### ISSUE TITLE
How to do one hot encoding?

### ISSUE THREAD

**Issue by nilesharma** [thuml/HashNet#16]
Data: Suppose I have 10 folders with 10 images (total 10*10=100) images

Question : what will be the one hot encoding of the 9th class and 7th image?
Question 2: Can there be only 10 digit one hot encoding eg (img1.jpg 0 0 0 0 0 0 0 0 0 1)?

Ps when i tried with only single input as (img1.jpg 1) it gives me the below error

[cloudera@quickstart src]$ python train.py --gpu_id 0 --dataset coco --prefix resnet50_hashnet --hash_bit 48 --net ResNet50 --lr 0.0003 --class_num .1
{'class_num': 0.1, 'l_threshold': 15.0, 'q_weight': 0, 'sigmoid_param': 0.20833333333333334, 'l_weight': 1.0}
Traceback (most recent call last):
  File "train.py", line 278, in <module>
    train(config)
  File "train.py", line 145, in train
    transform=prep_dict["train_set1"])
  File "/home/cloudera/Capstone/HashNet-master/pytorch/src/data_list.py", line 71, in __init__
    imgs = make_dataset(image_list, labels)
  File "/home/cloudera/Capstone/HashNet-master/pytorch/src/data_list.py", line 18, in make_dataset
    images = [(val.split()[0], np.array([int(la) for la in val.split()[1:]])) for val in image_list]
ValueError: invalid literal for int() with base 10: 'Caves/1._maxresdefault.jpg'

**Comment by caozhangjie** [comment]
img1.jpg 0 0 0 0 0 0 0 0 0 1 is OK if you have ten classes. img1.jpg 1 cannot be possible since you cannot have only one class in your dataset anyway.
