### ISSUE TITLE
Imagenet snapshot

### ISSUE THREAD

**Issue by nilesharma** [thuml/HashNet#19]
Hi, Can you please share the output/snapshot of the train/test for the model which is been ran already by you. As this is taking too long to execute the code in my machine. Thanks in advance

**Comment by caozhangjie** [comment]
I have already my snapshot here. https://drive.google.com/drive/folders/0B7IzDz-4yH_HOXdoaDU4dk40RFE?usp=sharing. You can see the instructions in caffe/README.md.

**Comment by nilesharma** [comment]
Hi Zhangjie,

Thanks for quick response, is the link same for the pytorch version(not
caffe)?

**Comment by caozhangjie** [comment]
I'm sorry but the pytorch version is not provided. The Pytorch Code trained on ImageNet does not have that performance now and we will revise the code soon. If you are urgent to predict codes, you can use our instructions in caffe and predict codes with caffe.
