### ISSUE TITLE
Some issues regarding the dataset

### ISSUE THREAD

**Issue by yuewuqing2224** [thuml/HashNet#20]
Hi, I just looked into the pytorch version of your code and I wonder if you could help clarify some points.

(1) ImageNet-100 train.txt consists of 13000 images. So I assume the reported results are from using 130 images per class during training?

(2) NUS_WIDE in caffe has 81 classes but only 21 classes in pytorch folder. Are the files in pytorch folder the result of selecting only the images with the 21 most frequent labels?

Thank you for answering my questions.

**Comment by caozhangjie** [comment]
(1) Yes, you are right.
(2) I'm sorry we put the wrong dataset in NUS_WIDE directory. We will change them. Thank you.
