### ISSUE TITLE
你好，非常感谢分享的NUS数据集，但是下载解压发现数据的图片比原始要少

### ISSUE THREAD

**Issue by SCUT-chenjia** [thuml/HashNet#26]
我只得到了223496张图片，一共269648张啊

**Comment by caozhangjie** [comment]
我们下载的时候部分图片链接失效，所以少了很多

**Comment by jing-1227** [comment]
> 我只得到了223496张图片，一共269648张啊

你好，请问可以提供一下这个nus数据集吗？我下载了，但是说源文件损坏了，解压不了

**Comment by Mahiro2211** [comment]
我的天啊
