### ISSUE TITLE
Why take two batches as input

### ISSUE THREAD

**Issue by MaxChanger** [thuml/HashNet#27]
Hello, I have some problems in reading and understanding the code.
- First, why two batches need to be taken from a data set？
- Second , the two batch form the same data set are different or same ?
Hope to your answer, thanks.

![image](https://user-images.githubusercontent.com/35401968/57590431-45353000-755e-11e9-9552-f551f452d096.png)

**Comment by chenshen03** [comment]
the same problem @caozhangjie

**Comment by chenshen03** [comment]
because the input is pair-wise

**Comment by MaxChanger** [comment]
> because the input is pair-wise

But, why do you choose read the pair-wise image from two different batch, in one batch, for example, batch_size = 64,  image[i] can be organized to pair-wise with other 63 image[j], j != i.

**Comment by chenshen03** [comment]
I just did an experiment to change the code of `train.py` and `loss.py` as follows:

**train.py:**
![image](https://user-images.githubusercontent.com/20432947/58074601-3e4e9300-7bd8-11e9-8555-767de450d1dd.png)

**loss.py:**
![image](https://user-images.githubusercontent.com/20432947/58074677-6b9b4100-7bd8-11e9-9fba-4a37c704c151.png)

The result is a litter better than the original version, which means the codes can be simplified by only one input branch.

![image](https://user-images.githubusercontent.com/20432947/58074717-8372c500-7bd8-11e9-82b2-779181aa6eb1.png)

**Comment by MaxChanger** [comment]
Thank you very much !
