### ISSUE TITLE
Some question about my result

### ISSUE THREAD

**Issue by prettyq** [thuml/HashNet#3]
Hi, I had download your nuswide_81_48_bits.caffemodel and nuswide.tar.gz dataset , and do it as follows:

`python models/predict/nuswide_81/predict_parallel.py --gpu 1 --model_path ./models/train/nuswide_81/caffemodel/nuswide_81_48_bits.caffemodel --save_path ./models/predict/nuswide_81/`

However, the result is 54.96.  Do you know why it happens?

**Comment by caozhangjie** [comment]
There is some bug in the test code since the last modification. I have fixed this bug now.
