### ISSUE TITLE
The mAP of ImageNet is different from that on paper

### ISSUE THREAD

**Issue by chenshen03** [thuml/HashNet#31]
Can you share the parameters setting on ImageNet?

I follow the settings described on paper, but obtain a bad result:

![image](https://user-images.githubusercontent.com/20432947/63486795-7ddc9200-c4db-11e9-8eab-f60f2ecf282f.png)

**Comment by caozhangjiex** [comment]
The pytorch version of the code perform badly on ImageNet. We do not find the reason yet. Please use the caffe version if you want to run on ImageNet.

**Comment by chenshen03** [comment]
Could you share the link of caffe version? I can't find it on github.

**Comment by caozhangjiex** [comment]
check caffe directory

**Comment by chenshen03** [comment]
I just directly use your pretrained caffe's model to evaluate the mAP on ImageNet, and some results are as follows;
- 16bit: 0.4643
- 32bit: 0.5934

However, the results on your paper are as follows:
![image](https://user-images.githubusercontent.com/20432947/63495118-ce5eea00-c4f1-11e9-8325-c27133d778f1.png)

What makes this difference?

**Comment by caozhangjie** [comment]
Maybe it is because the caffe framework changes or other reason such as initialization. I'm sure it can reproduce the results at publishing.

**Comment by chenshen03** [comment]
I retrained the model and obtain an ideal result. Thank you~

**Comment by TreezzZ** [comment]
> I retrained the model and obtain an ideal result. Thank you~

请问是如何训练的？我用PyTorch在DSH、DHN和HashNet三个算法上复现，均是在Imagenet数据集上表现奇差。

**Comment by chenshen03** [comment]
> > I retrained the model and obtain an ideal result. Thank you~
> 
> 请问是如何训练的？我用PyTorch在DSH、DHN和HashNet三个算法上复现，均是在Imagenet数据集上表现奇差。

我之前跑过HashNet的作者提供的PyTorch版本，也自己复现过，但是在ImageNet上表现都不好，但我感觉你的表现好像比我的还更差。不过如果直接跑caffe的版本的话，结果和论文差不多。
