### ISSUE TITLE
Can't find the image file.

### ISSUE THREAD

**Issue by forrestlly** [thuml/HashNet#8]
Hello authors !
Recently I download your provided NUS-WIDE dataset (Thanks for your sharing) and I find a question.
In your readme, it says:
For NUS-WIDE, you need to move the nus_wide.tar.gz to ./data/nuswide_81 and extract the file there.
But I find the extracted images don't have the same names as in the train.txt.
such as in the train.txt the first file is: 
./data/nuswide_81/images/98796_381708603_f86eb60ccf_m.jpg 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
But I don't find the 98796_381708603_f86eb60ccf_m.jpg in the extracted images.
So I feel puzzled.
Thank you for answering my question.

**Comment by caozhangjie** [comment]
I download the dataset and I can find the `98796_381708603_f86eb60ccf_m.jpg' in the extracted images. Maybe you can re-download the dataset and check again.

**Comment by forrestlly** [comment]
Oh sorry I mistake the tar.gz and I don't find the elementary error.
Thank you!

**Comment by forrestlly** [comment]
./data/nuswide_81/images/180992_2635942202_93fed1576c_m.jpg 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

**Comment by forrestlly** [comment]
Thanks for the dataset NUS-WIDE sharing! And I have a question about the NUS-WIDE dataset labels.
Some images' labels are all zeros. And Could you introduce the all zeros' meanings and how I can deal with such labels with other non-zeros labels( they are dissimilar?)  Thank you very much !
such as in the train.txt the second row:
./data/nuswide_81/images/180992_2635942202_93fed1576c_m.jpg 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

**Comment by caozhangjie** [comment]
Yes, they are dissimilar. It will decrease the performance a little. But if you use it to compare with other methods, it is still a fair comparison since all the methods suffer equally from this.

**Comment by forrestlly** [comment]
Thank you for your answer! : )
so the all zeros images have the meaning of that they don't belong to any class ? 
feeling a little puzzled..

**Comment by caozhangjie** [comment]
Yes

**Comment by forrestlly** [comment]
Thank you! you're so nice.
